### PR TITLE
Feature: Fixed-size arrays (size <= 4) can now be accessed by x, y, z, w or r, g, b, a

### PR DESCRIPTION
**Pull request by judah-caruso**
This PR adds a new feature to Onyx that allows basic array programming support. This means arrays, rather than structs, can be used as common linear algebra types (as well as colors), opening up more language features around this in the future.

## How it works

When accessing fixed-size arrays of size <= 4 by field instead of index, we check if the field matches `x, y, z, w` or `r, g, b, a` and if the accessor is within the array's bounds. If valid, we map the named field to the expected index and offset.

## Examples
```odin
// Vector3 example
v := f32.[ 1, 1, 1 ];

v[0] = 2; // Normal array access is still valid
v.x  = 2; // Because v is [3]f32, 'x', 'y', and 'z' are valid fields to access
v.y  = 3; 
v.z  = 4;
v.w  = 0; // Will not work, the same as v[3]

// v is now [ 2, 3, 4 ]

// Color example
c: [4]u8; // A simple RGBA8 color

c[0], c[1] = 0, 0; // Works as expected
c.r,  c.g  = 0, 0; // Is allowed now. 'x', 'y', 'z', 'w' are still valid fields
c.b,  c.a  = 255, 255;

// c is now [ 0, 0, 255, 255 ]
```

### CODE REVIEW

**Comment by brendanfh** [comment]
There is another feature I want to work on which is refactoring how `where` clauses work that would tie into this nicely. Currently `where` clauses can only work with `interface`s, but I would like them to work with any compile-time boolean expression. That way there could be something like:

```odin
#operator + (a, b: [$N] $T/core.intrinsics.types.type_is_number) -> [N] T
    where N <= 4
{
    res: [N] T;
    for i: N do res[i] = a[i] + b[i];
    return res;
}
```

This can already be implemented without the `N <= 4` constraint, and maybe that is okay? Does it make sense to limit operations to fixed-size arrays less than 4 elements in size?

**Comment by judah-caruso** [comment]
Should I include the `where` clause work/operator overloads for arrays in this PR?

**Comment by brendanfh** [comment]
I would say create a new pull-request to keep the tracking a little bit clearer. I'll merge this now.

**Comment by judah-caruso** [comment]
Awesome, will work on those later today!

**Pull request merged**
